### ISSUE TITLE
Runtime error with Unity container

### ISSUE THREAD

**Issue by claudiagoga** [beyourmarket/beyourmarket#66]
Hi everyone, I'm getting a runtime error on my app, after multiple deployements to Azure. I've tried restarting the service but still no luck and I'm not sure I could delete temp files in Azure.

Here is the event data. Does anyone have any ideas about why this occurs? Thanks!

> <Event>
> <System>
> <Provider Name="ASP.NET 4.0.30319.0"/>
> </System>
> <EventData>
> <Data>An unhandled exception has occurred.</Data>
> <Data>D:\home\site\wwwroot\</Data>
> <Data>w3wp.exe</Data>
> <Data>IIS APPPOOL\CareToPets</Data>
> <Data>InvalidOperationException</Data>
> <Data>
> The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation.. at System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) at System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) at System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) at System.Web.Compilation.BuildManager.ExecutePreAppStart() at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() at WebActivatorEx.ActivationManager.RunActivationMethods[T](Boolean designerMode) at WebActivatorEx.ActivationManager.RunPreStartMethods(Boolean designerMode) at WebActivatorEx.ActivationManager.Run() Method not found: 'Microsoft.Practices.Unity.IUnityContainer BeYourMarket.Core.ContainerManager.GetConfiguredContainer()'. at BeYourMarket.Web.App_Start.UnityWebActivator.Start()
> </Data>
> <Data>
> at System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) at System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) at System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) at System.Web.Compilation.BuildManager.ExecutePreAppStart() at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)
> </Data>
> </EventData>
> </Event>

**Comment by sohailqureshi** [comment]
Have you tried rebuilding the entire project prior to deploying?....

**Comment by sparra1000** [comment]
@claudiagoga  Did you ever find a solution to this?  I am getting the same error, it fixes with a solution clean but keeps coming back intermittently locally and on Azure:
MissingMethodException: Method not found: 'Microsoft.Practices.Unity.IUnityContainer BeYourMarket.Core.ContainerManager.GetConfiguredContainer()
in BeYourMarket.Web.App_Start.UnityWebActivator.Start() in C:\BeYourMarket.Web\App_Start\UnityMvcActivator.cs
